// <auto-generated />
namespace CraCode.DBLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class ColCountryStateAndCityAddedInStudentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColCountryStateAndCityAddedInStudentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202303120853251_ColCountryStateAndCityAddedInStudentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
